CREATE TABLE ESPECIALIDADE (
sigla CHAR(2) PRIMARY KEY,
descricao VARCHAR(30)
)

/

CREATE TABLE PACIENTE (
cpf NUMERIC(11) PRIMARY KEY,
logradouro VARCHAR(10),
cep NUMERIC(8),
bairro VARCHAR(30),
uf CHAR(2),
cidade VARCHAR(10),
nome_paciente VARCHAR(10),
sexo CHAR(1)
)

/

CREATE TABLE MEDICO (
nome_medico VARCHAR(30),
crm NUMERIC(9) PRIMARY KEY,
sigla CHAR(2),
FOREIGN KEY(sigla) REFERENCES ESPECIALIDADE (sigla)
)

/

CREATE TABLE TELEFONE_PACIENTE (
telefone_PK INTEGER PRIMARY KEY,
telefone VARCHAR(11),
cpf_FK NUMERIC(11),
FOREIGN KEY(cpf_FK) REFERENCES PACIENTE (cpf)
)

/

CREATE TABLE ATENDIMENTO (
crm NUMERIC(9),
cpf NUMERIC(11),
data DATETIME,
hora DATETIME,
valor NUMERIC(10,2),
PRIMARY KEY(crm,cpf,data,hora),
FOREIGN KEY(crm) REFERENCES MEDICO (crm),
FOREIGN KEY(cpf) REFERENCES PACIENTE (cpf)
)

/